### ISSUE TITLE
Add node_modules and other output directories to .dockerignore

### ISSUE THREAD

**Issue by chantzlarge** [go-nostr/nostr#20]
## Prerequisites

- [x] I have searched the existing issues and I'm sure this is not a duplicate.
- [ ] If reporting a bug, I have followed the necessary troubleshooting steps.
- [x] If suggesting a feature, I have explained my reasoning and use case.

### If suggesting a feature:

**Feature description:**

Add `node_modules` and other output directories to `.dockerignore`.

**Use case:**

When building Docker images, it is important to exclude unnecessary files and directories to reduce the size of the image and improve build times. In our current monorepo, the `node_modules` directory, as well as other output directories like `dist`, `public`, and `resources`, should be added to `.dockerignore` to prevent them from being included in the Docker image.

By excluding these directories, we can optimize the image size and build times, which can lead to better overall performance.

**Alternative solutions:**

Manually deleting the output directories before running the `docker build` command is an alternative, but it is not a sustainable solution. Ignoring these directories in the `.dockerignore` file ensures they are consistently excluded during the build process.

**Additional context:**

Relevant directories to be added to `.dockerignore`:

- `node_modules`
- `internal/client/dist`
- `internal/docs/public`

**Comment by vavrajosef** [comment]
Hello, I would like to work on this. Please assign it to me.

**Comment by chantzlarge** [comment]
> Hello, I would like to work on this. Please assign it to me.

Great, I've assigned the issue to you!

If you have any questions, don't hesitate to ask. To start, fork the repo, create a new branch, and update the .dockerignore file. Please test your changes locally and then submit a PR for review.

Thanks for your contribution, and we're looking forward to your work!

**Comment by chantzlarge** [comment]
@vavrajosef I added a few entries to the .dockerignore while wrestling with the CI configurations. Consider adding some more as needed.
